name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - fix-ci
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    name: ${{ matrix.os }} / GHC ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        include:
          - os: macos-latest
            ghc: system

    steps:
      - uses: actions/checkout@v4
      - run: which -a pkg-config
      - run: pkg-config --list-all | grep openssl
      - run: export PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig"
      - run: pkg-config --list-all | grep openssl
      - name: Set OpenSSL Paths
        run: |
          echo "CPATH=$(brew --prefix openssl)/include" >> $GITHUB_ENV
          echo "LIBRARY_PATH=$(brew --prefix openssl)/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix openssl)/lib/pkgconfig" >> $GITHUB_ENV
      - uses: hspec/setup-haskell@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - uses: sol/run-haskell-tests@v2
        with:
          caching: true
